style changes to evaluator and writer
JustinHuPrime/DataPackCrafter pull request #43
Opened 2021-09-30 21:57 UTC by JustinHuPrime

- will add pre-commit hook to run prettier

2021-09-30 22:31 UTC, kilowatt- submitted a review, later dismissed

2021-10-01 01:58 UTC, jlu5 requested changes
Can we defer this until the evaluator part 2 is finished? It's going to be an awful mess of merge conflicts otherwise..

2021-10-01 02:53 UTC, JustinHuPrime commented
> Can we defer this until the evaluator part 2 is finished? It's going to be an awful mess of merge conflicts otherwise..

Fair enough

2021-10-06 02:29 UTC, jlu5 approved these changes

2021-10-06 03:07 UTC, merged